### PR TITLE
Create notifyme.json

### PR DESCRIPTION
**Pull request by rodistic**
# Please double check your fork for the following:

- [X] Creating this pull request.
- [x] Cover image is uploaded on imgur.
- [x] Cover image ends in `.jpg, .png, or .jpeg`
- [x] Tags of resources only includes tags supplied on front-page

**Fill each step with 'X' if requirements are met.**

### CODE REVIEW

**Comment by jovanivanovic** [comment]
@rodistic the cover has to be uploaded to Imgur.

**Comment by rodistic** [comment]
changed it

**Comment by jovanivanovic** [comment]
@rodistic not a link to Imgur page but a direct link to an image uploaded on Imgur

**Comment by rodistic** [comment]
now?

**Pull request merged**
