### PR TITLE
Create MongoDB-Wrapper

### PR DESCRIPTION
**Pull request by DiTheRX**
# Please double check your fork for the following:

- [X] Creating this pull request.
- [x] Cover image is uploaded on imgur.
- [x] Cover image ends in `.jpg, .png, or .jpeg`
- [x] Tags of resources only includes tags supplied on front-page

**Fill each step with 'X' if requirements are met.**

### CODE REVIEW

**Comment by Stuyk** [comment]
I think the Readme needs some instructions and general cleanup.

**Comment by DiTheRX** [comment]
> I think the Readme needs some instructions and general cleanup.

I don’t understand, can you explain? I have not added information to the readme file yet

**Comment by ThomasMarangoni** [comment]
Add instruction to your README.md how to use the resource and Please add `"cli": false` to your json

**Comment by Stuyk** [comment]
No updates since creation. Closing.

**Pull request closed without merging**
