### PR TITLE
TutoHacks new Developer

### PR DESCRIPTION
**Pull request by TutoHacks**
# Please double check your fork for the following:

- [X] Creating this pull request.
- [X] Cover image is uploaded on imgur.
- [X] Cover image ends in `.jpg, .png, or .jpeg`
- [X] Tags of resources only includes tags supplied on front-page

**Fill each step with 'X' if requirements are met.**

### CODE REVIEW

**Comment by ThomasMarangoni** [comment]
you are missing the "cli" tag in your json file

**Comment by TutoHacks** [comment]
i added the cli tag.

**Comment by ThomasMarangoni** [comment]
No i ment, "cli": false or "cli": true see here: https://lmddgtfy.net/?q=node%20js%20Missing%20Driver%20Error%3A%20Wrong%20Driver

**Comment by TutoHacks** [comment]
Please make sure you have Node.JS 13+

**Comment by TutoHacks** [comment]
i dont know what do you mean?
in my config.json i write: "webhookaktiv": "true",

**Comment by ThomasMarangoni** [comment]
compare your alt:V Hub json file ( resources/TutoHacks/loginsystem.json) with this https://github.com/altmp/altv-hub#example-json-structure-for-resource

I've seen i copied the wrong link in my older message, sorry

**Comment by TutoHacks** [comment]
Now i fixed it :)

**Pull request merged**
